apiVersion: 1

datasources:
  - name: DQ PostgreSQL
    uid: dq-postgresql
    type: postgres
    access: proxy
    url: postgres:5432
    database: dq_monitoring
    user: dq_user
    secureJsonData:
      password: dq_password
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
